import { ArrowUpRight, FileCheck2, Scale, ShieldCheck } from "lucide-react";
import { useEffect } from "react";
import { Eyebrow, PageFrame, Reveal, SmartLink } from "../components/SiteChrome";

export default function LicensesPage() {
    useEffect(() => {
        document.title = "Licenses · YRecall";
        document.querySelector<HTMLMetaElement>('meta[name="description"]')?.setAttribute("content", "License and attribution information for YRecall and the YRecall website.");
        window.scrollTo({ top: 0, behavior: "auto" });
    }, []);
    return <PageFrame>
        <section className="page-hero page-hero--legal"><div className="shell page-hero__inner"><Reveal><Eyebrow>Open work, credited clearly</Eyebrow><h1>Licenses &amp;<br /><span>attributions.</span></h1><p>A practical index of the open-source foundations and creative materials used across the YRecall website.</p></Reveal><Reveal className="legal-mark reveal-delay-1"><span><Scale size={28} /></span><small>LYFSPOT / CREDITS</small></Reveal></div></section>
        <section className="section section--legal"><div className="shell license-layout"><Reveal className="license-intro"><Eyebrow tone="lime">How to read this page</Eyebrow><h2>Good products<br /><span>stand on shoulders.</span></h2><p>YRecall includes open-source software and platform services. We preserve the rights of their authors and make this summary available for transparency. Notices may be updated as dependencies change.</p><SmartLink className="inline-link" to="/support">Questions about an attribution <ArrowUpRight size={15} /></SmartLink></Reveal><Reveal className="license-list reveal-delay-1"><div className="license-callout"><ShieldCheck size={20} /><p>Unless a component says otherwise, its original license remains with its authors. YRecall branding, original copy, illustrations, and product materials remain the property of LYFSpot or their respective creators.</p></div><article className="license-item"><span>01</span><div><h2>Application foundations</h2><p><strong>React</strong>, <strong>React DOM</strong>, <strong>React Router</strong>, <strong>Vite</strong>, and <strong>TypeScript</strong> are used under permissive open-source licenses, including MIT. Their notices and source projects are maintained by their respective communities.</p></div></article><article className="license-item"><span>02</span><div><h2>Interface and interaction</h2><p><strong>Lucide</strong> icons are used under the ISC license. Radix UI primitives and related utilities are used under their published open-source licenses. These projects remain independent of LYFSpot.</p></div></article><article className="license-item"><span>03</span><div><h2>Testing and build tooling</h2><p><strong>Vitest</strong>, <strong>Playwright</strong>, ESLint, PostCSS, Tailwind CSS, and their transitive dependencies are development tools distributed under the licenses published by their maintainers.</p></div></article><article className="license-item"><span>04</span><div><h2>Third-party services</h2><p>Fonts, hosting, analytics, app distribution, email, and other services may have their own terms and attribution requirements. YRecall does not claim ownership of third-party names, marks, or services.</p></div></article><article className="license-item"><span>05</span><div><h2>Request a complete notice</h2><p>For a dependency-specific notice or a question about an attribution, contact <a href="mailto:lyfspot@zohomail.in">lyfspot@zohomail.in</a>. Please include the package or material you are asking about.</p></div></article><div className="license-footer-note"><FileCheck2 size={17} /><span>Last reviewed August 06, 2026 · See also <SmartLink to="/legal/terms">Terms of service</SmartLink> and <SmartLink to="/legal/privacy">Privacy policy</SmartLink>.</span></div></Reveal></div></section>
    </PageFrame>;
}
